ALTER TABLE event_results ADD COLUMN promo_sales REAL NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS event_promo_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  result_id INTEGER NOT NULL REFERENCES event_results(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  price REAL NOT NULL DEFAULT 0
);
